// pages/machines/[host]/apps.tsx
import { useEffect, useState } from "react";

import fetchMachine from "../../../lib/fetch-machine";
import { AppProps } from "../../../lib/interfaces/app-props.interface";
import styles from "./apps.module.scss";

export default function Apps({ machine }: AppProps) {
  return (
    <>
      <div className={styles.bg}></div>
      <div className="container">
        {machine?.containers?.map((container) => (
          <div key={container.Id} className={styles.app}>
            <div className={styles.title}>
              <img src={container.app?.logo} alt="" />
              {!container.app?.name ? (
                <span>{container.Names?.[0]?.replace("/", "")}</span>
              ) : (
                <span>
                  {container.app?.name} {container.app?.version}
                </span>
              )}
            </div>

            <div className={styles.buttons}>
              <button>
                <img src="/icons/solid/trash-alt.svg" alt="" />
                Uninstall
              </button>

              <button>
                <img src="/icons/solid/pause.svg" alt="" />
                Stop
              </button>

              <button>
                <img src="/icons/solid/play.svg" alt="" />
                Start
              </button>
            </div>

            <ul>
              <li>
                Status:
                <span>{container.State?.Status}</span>
              </li>

              <li>
                Uptime: <span>{container.Status}</span>
              </li>

              {/* <li>
                  Memory Usage:
                  <span>{container.stats?.memory_stats?.usage}</span>
                  <div className="memory"></div>
                </li> */}

              <li>
                CPU Usage
                <div className={styles.memory}></div>
              </li>

              <li>
                Image: <span>{container.Image}</span>
              </li>

              <li>
                Created At: <span>{container.Created}</span>
              </li>

              {/* <li>
        Ports:
        <ul>
            <li>
                <span> {item.PrivatePort || 'N/A'} </span> ->
                <span> {item.PublicPort || 'N/A'}</span>
            </li>
        </ul>
    </li>
    <li >
        Mounts:
        <ul>
            <li >
                <span> {item.Source || 'N/A'} </span> 
                <span> {item.Destination || 'N/A'}</span>
            </li>
        </ul>
    </li>


    <ul className="variables">
        <li >
            <label >{item.name}</label>
            <input type="text" readOnly value="item.value">
        </li>
    </ul> */}
            </ul>
          </div>
        ))}
      </div>
    </>
  );
}

// src/app/pages/apps/apps.component.ts
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Container } from '../../interfaces/docker.namespace';

import { ShellNode } from '../../interfaces/shell-node.interface';
import { ShellService } from '../../shared/shell.service';

@Component({
  selector: 'app-apps',
  templateUrl: './apps.component.html',
  styleUrls: ['./apps.component.scss']
})
export class AppsComponent implements OnInit {


  public get model(): ShellNode {
    return this.shellService.selectedNode;
  }

  templates = [];
  containers: Container[] = [];
  apps = []

  memoryCharts = {}

  constructor(
    public readonly shellService: ShellService,
    private readonly changeRef: ChangeDetectorRef) {
    // setInterval(() => {
    //   this.memoryCharts = this.shellService.memoryCharts;
    //   this.changeRef.detectChanges();
    // }, 1000)
  }

  async ngOnInit() {
    this.apps = await this.shellService.apps();

    this.containers = this.shellService.selectedNode.containers.map((container) => {

      container.app = this.apps.find(p => '/' + p.container === container.Names[0]);

      return container;
    });

  }
  async removeContainer(container) {

  }
  async installApp(template) {

    await this.shellService.installApp(template);

  }


  async uninstallApp(appId) {

  }

}

<section class="box">

    <div class="title">
        Installed Apps
    </div>

    <div *ngFor="let container of containers" class="app">

        <div class="title">

            <img *ngIf="container.app?.logo" [src]="container.app?.logo" alt="">

            <span *ngIf="container.app">
                {{container.app.name}} {{container.app.version}}
            </span>

            <span *ngIf="!container.app">
                {{container.Names[0]?.replace('/','')}}
            </span>

        </div>


        <div class="stats">



        </div>

        <div class="buttons">
            <button (click)="removeContainer(container.Id)">
                <img src="assets/icons/solid/trash-alt.svg" alt="">
                Uninstall
            </button>

            <button *ngIf="!shellService.realtime[container.Id]?.container?.State.Paused"
                (click)="removeContainer(container.Id)">
                <img src="assets/icons/solid/pause.svg" alt="">
                Stop
            </button>

            <button *ngIf="shellService.realtime[container.Id]?.container?.State.Paused"
                (click)="removeContainer(container.Id)">
                <img src="assets/icons/solid/play.svg" alt="">
                Start
            </button>

        </div>



        <ul *ngIf="container">

            <li>
                Status:
                <span>
                    {{shellService.realtime[container.Id]?.container?.State?.Status }}
                </span>
            </li>

            <li>
                Uptime: <span>{{container.Status}}</span>
            </li>

            <li>
                Memory Usage:
                <span>
                    {{shellService.realtime[container.Id]?.stats?.memory_stats?.usage | bytes: 2}}
                </span>

                <div class="memory">
                    <ngx-charts-line-chart [legend]="false" [view]="[260,40]" [scheme]="'cool'" [showXAxisLabel]="false"
                        [showYAxisLabel]="false" [showGridLines]="false" [animations]="false"
                        [results]="shellService.memoryCharts[container.Id] || []">
                    </ngx-charts-line-chart>
                </div>

            </li>

            <li>
                CPU Usage

                <div class="memory">
                    <ngx-charts-line-chart [legend]="false" [view]="[260,40]" [scheme]="'cool'" [showXAxisLabel]="false"
                        [showYAxisLabel]="false" [showGridLines]="false" [animations]="false"
                        [results]="shellService.cpuCharts[container.Id] || []">
                    </ngx-charts-line-chart>
                </div>

            </li>

            <li>
                Image: <span>{{container.Image}}</span>
            </li>

            <li>
                Created At: <span>{{container.Created | mdate}}</span>
            </li>

            <li *ngIf="container?.Ports?.length">
                Ports:
                <ul>
                    <li *ngFor="let item of container.Ports">
                        <span> {{item.PrivatePort || 'N/A'}} </span> ->
                        <span> {{item.PublicPort || 'N/A'}}</span>
                    </li>
                </ul>
            </li>
            <li *ngIf="container?.Mounts">
                Mounts:
                <ul>
                    <li *ngFor="let item of container.Mounts">
                        <span> {{item.Source || 'N/A'}} </span> ->
                        <span> {{item.Destination || 'N/A'}}</span>
                    </li>
                </ul>
            </li>


            <ul class="variables">
                <li *ngFor="let item of container.app?.variables">
                    <label for="">{{item.name}}</label>
                    <input type="text" readonly [value]="item.value">
                </li>
            </ul>

        </ul>
    </div>
</section>
